-- Create holidays table
CREATE TABLE IF NOT EXISTS holidays (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    name_en TEXT NOT NULL,
    name_ar TEXT NOT NULL,
    category TEXT NOT NULL,
    is_enabled BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE holidays ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public read access
CREATE POLICY "Allow public read access" ON holidays
    FOR SELECT USING (true);

-- Create policy to allow authenticated update access (admin only)
CREATE POLICY "Allow authenticated update" ON holidays
    FOR UPDATE USING (auth.role() = 'authenticated');

-- Seed initial holidays
INSERT INTO holidays (key, name_en, name_ar, category) VALUES
('new_year', 'New Year''s Day', 'رأس السنة الميلادية', 'National'),
('coptic_christmas', 'Coptic Christmas', 'عيد الميلاد المجيد', 'Religious'),
('jan_25', 'January 25 Revolution / Police Day', 'ثورة ٢٥ يناير / عيد الشرطة', 'National'),
('sham_el_nessim', 'Sham El-Nessim', 'شم النسيم', 'National'),
('sinai_liberation', 'Sinai Liberation Day', 'عيد تحرير سيناء', 'National'),
('labor_day', 'Labor Day', 'عيد العمال', 'National'),
('eid_fitr', 'Eid al-Fitr', 'عيد الفطر المبارك', 'Religious'),
('arafat_day', 'Arafat Day', 'وقفة عرفات', 'Religious'),
('eid_adha', 'Eid al-Adha', 'عيد الأضحى المبارك', 'Religious'),
('islamic_new_year', 'Islamic New Year', 'رأس السنة الهجرية', 'Religious'),
('mawlid_al_nabi', 'Mawlid al-Nabi', 'المولد النبوي الشريف', 'Religious'),
('june_30', 'June 30 Revolution Day', 'ثورة ٣٠ يونيو', 'National'),
('july_23', 'July 23 Revolution Day', 'ثورة ٢٣ يوليو', 'National'),
('october_6', 'Armed Forces Day (October 6)', 'عيد القوات المسلحة (٦ أكتوبر)', 'National'),
('ramadan', 'Ramadan', 'شهر رمضان المبارك', 'Religious'),
('mothers_day', 'Mother’s Day', 'عيد الأم', 'Seasonal'),
('valentines_day', 'Valentine’s Day', 'عيد الحب', 'Seasonal'),
('back_to_school', 'Back to School', 'العودة للمدارس', 'Seasonal'),
('summer_vacation', 'Summer Vacation', 'إجازة الصيف', 'Seasonal'),
('black_friday', 'Black Friday / White Friday', 'الجمعة البيضاء', 'Seasonal'),
('national_events', 'National Events', 'مناسبات وطنية', 'National')
ON CONFLICT (key) DO NOTHING;
